version: "3.8"
services: 
  service1:
    container_name: which_animal_am_i_server
    image: aguamonkey/which_animal_am_i_server
    build: ./service1
    ports: 
    - published: 5000
      target: 5000
    environment:
      DATABASE_URI: ${DATABASE_URI}
  service2:
    container_name: animal_name_api 
    image: aguamonkey/animal_name_api
    build: ./animal_api
  service2:
    container_name: animal_name_api 
    image: aguamonkey/animal_name_api
    build: ./animal_api

    