---
# tasks file for nginx

# nginx install
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Create a template /etc/file.conf
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config


- name: Restart nginx when required
  service:
    name: nginx
    state: restarted
  when: nginx_config.changed 