- hosts: all
  become: true
  roles:
  - install-docker

- hosts: managers
  become: true
  roles:
  - swarm-manager

- hosts: workers
  become: true
  roles:
  - swarm-worker

- hosts: load_balance
  become: true
  roles:
  - nginx