---
# tasks file for install-docker
- name: "Install dependencies"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: "Get Docker APT key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: "Add Docker APT Repo"
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: "Install Docker"
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: "Add User to Docker Group"
  user:
    name: jenkins
    groups: docker
    append: yes

- name: "Install Docker with pip"
  pip:
    name: docker
    executable: pip3
